import CollapsingTowers.TwoLevelMut.SyntacticTyping.Effect
import CollapsingTowers.TwoLevelMut.SyntacticTyping.Ty
import CollapsingTowers.TwoLevelMut.SyntacticTyping.Env
import CollapsingTowers.TwoLevelMut.SyntacticTyping.Typing
import CollapsingTowers.TwoLevelMut.SyntacticTyping.Weakening
