import CollapsingTowers.TwoLevelBasic.LogicalEquiv.LogicalRelation
import CollapsingTowers.TwoLevelBasic.LogicalEquiv.Compatibility
import CollapsingTowers.TwoLevelBasic.LogicalEquiv.Fundamental
import CollapsingTowers.TwoLevelBasic.LogicalEquiv.Transitivity
import CollapsingTowers.TwoLevelBasic.LogicalEquiv.Soundness
import CollapsingTowers.TwoLevelBasic.LogicalEquiv.Completeness
