import CollapsingTowers.TwoLevelFinal.OperationalSemantics.Value
import CollapsingTowers.TwoLevelFinal.OperationalSemantics.Store
import CollapsingTowers.TwoLevelFinal.OperationalSemantics.EvalCtx
import CollapsingTowers.TwoLevelFinal.OperationalSemantics.SmallStep
