import CollapsingTowers.TwoLevelRec.SyntacticTyping.Typing
import CollapsingTowers.TwoLevelRec.SyntacticTyping.Weakening
import CollapsingTowers.TwoLevelRec.SyntacticTyping.Shrinking
import CollapsingTowers.TwoLevelRec.SyntacticTyping.PresvSubst
import CollapsingTowers.TwoLevelRec.SyntacticTyping.PresvMaping
import CollapsingTowers.TwoLevelRec.SyntacticTyping.PresvHead
