import CollapsingTowers.TwoLevelRec.Semantic.Value
import CollapsingTowers.TwoLevelRec.Semantic.EvalCtx
import CollapsingTowers.TwoLevelRec.Semantic.SmallStep
import CollapsingTowers.TwoLevelRec.Semantic.Congruence
import CollapsingTowers.TwoLevelRec.Semantic.Deterministic
import CollapsingTowers.TwoLevelRec.Semantic.Confluence
import CollapsingTowers.TwoLevelRec.Semantic.Refine
