import CollapsingTowers.TwoLevelRec.OperationalSemantics.Value
import CollapsingTowers.TwoLevelRec.OperationalSemantics.EvalCtx
import CollapsingTowers.TwoLevelRec.OperationalSemantics.SmallStep
import CollapsingTowers.TwoLevelRec.OperationalSemantics.Congruence
import CollapsingTowers.TwoLevelRec.OperationalSemantics.Deterministic
import CollapsingTowers.TwoLevelRec.OperationalSemantics.Confluence
import CollapsingTowers.TwoLevelRec.OperationalSemantics.Refine
