import CollapsingTowers.TwoLevelMut.OperationalSemantics.Value
import CollapsingTowers.TwoLevelMut.OperationalSemantics.Store
import CollapsingTowers.TwoLevelMut.OperationalSemantics.EvalCtx
import CollapsingTowers.TwoLevelMut.OperationalSemantics.SmallStep
import CollapsingTowers.TwoLevelMut.OperationalSemantics.Congruence
