import CollapsingTowers.TwoLevelBasic.Semantic.Value
import CollapsingTowers.TwoLevelBasic.Semantic.EvalCtx
import CollapsingTowers.TwoLevelBasic.Semantic.SmallStep
import CollapsingTowers.TwoLevelBasic.Semantic.Congruence
import CollapsingTowers.TwoLevelBasic.Semantic.Deterministic
import CollapsingTowers.TwoLevelBasic.Semantic.Confluence
