import CollapsingTowers.TwoLvLBasic.SyntacticTyping.Typing
import CollapsingTowers.TwoLvLBasic.SyntacticTyping.Weakening
import CollapsingTowers.TwoLvLBasic.SyntacticTyping.Shrinking
import CollapsingTowers.TwoLvLBasic.SyntacticTyping.PresvSubst
import CollapsingTowers.TwoLvLBasic.SyntacticTyping.PresvMaping
import CollapsingTowers.TwoLvLBasic.SyntacticTyping.PresvHead
