import CollapsingTowers.TwoLevelRec.Syntax.Effect
import CollapsingTowers.TwoLevelRec.Syntax.Basic
import CollapsingTowers.TwoLevelRec.Syntax.SyntacticTrans
import CollapsingTowers.TwoLevelRec.Syntax.Fv
import CollapsingTowers.TwoLevelRec.Syntax.Closedness
