import CollapsingTowers.TwoLevelRec.LogicalEquiv.LogicalRelation
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Compatibility
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Fundamental
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Transitive
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Soundness
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Completeness
