import CollapsingTowers.TwoLevelRec.LogicalEquiv.LogicalRelation
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Compatibility
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Fundamental
import CollapsingTowers.TwoLevelRec.LogicalEquiv.Soundness
