import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvSubst
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvMaping
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvCtx
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvPure
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvReflect
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.Preservation
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.Progress
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.Soundness
