import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvSubst
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvMaping
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvCtx
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvHead
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvReflect
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.Preservation
