import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvSubst
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvMaping
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.PresvHead
import CollapsingTowers.TwoLevelRec.SyntacticSoundness.Preservation
