name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
      - name: build
        run: |
          lake build CollapsingTowers.TwoLevelBasic.SemEquiv.Preservation
          lake build CollapsingTowers.TwoLevelFull.Soundness
          lake build CollapsingTowers.TwoLevelFull.Examples.Defs
